// <auto-generated />
using System;
using Api_Restful.AccesData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api_Restful.AccesData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210618022510_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api_Restful.Domain.Entities.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega");

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salon"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Pedidos Ya"
                        });
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia");

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "http://malevamag.com/wp-content/uploads/2017/11/Ceviche-cremosos-Puerta-del-Inca-1200x800.jpg",
                            Ingredientes = "dados de salmón marinados en jugo de lima, crema de ají amarillo, chips y maíz frito",
                            Nombre = "Ceviche Cremoso",
                            Precio = 250,
                            Preparacion = "Un plató típico de la gastronomía peruana",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "http://malevamag.com/wp-content/uploads/2017/11/Inmigrante_12__rp-1200x800.jpg",
                            Ingredientes = "Jamón marinado y glaseado a la parrilla, huevo a baja temperatura con polvo de aceitunas negras, salteado de arvejas, cebolla encurtida y papas fritas a la provenzal.",
                            Nombre = "Gramajo",
                            Precio = 195,
                            Preparacion = "Una receta que data de la época de la gran inmigración europea a la Argentina y que constituye un clásico de nuestra gastronomía.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "http://malevamag.com/wp-content/uploads/2017/11/Empanada-de-Ciervo-Alos-1198x800.jpg",
                            Ingredientes = "La masa es casera y el relleno se prepara con carne de ciervo que fue braseado por muchas horas.",
                            Nombre = "Empanadas de Ciervo",
                            Precio = 195,
                            Preparacion = "Se sirve con una fresca ensalada de rabanitos y verdes, más una salsa de tomates con limón que potencia todos los sabores.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "http://malevamag.com/wp-content/uploads/2017/11/Pizza-Frita-Ike-Milano-1200x800.jpg",
                            Ingredientes = "Sale con mozzarella, tomate y albahaca fresca",
                            Nombre = "Pizza Frita Margherita",
                            Precio = 140,
                            Preparacion = "Un plato típico de la cocina callejera napolitana.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "http://malevamag.com/wp-content/uploads/2017/11/Buller_17_rp-1-1200x800.jpg",
                            Ingredientes = "Crocantes capas de Nachos al horno, con salsa de especial de tomates, queso fundido, cheddar y verdeo",
                            Nombre = "Nachos",
                            Precio = 290,
                            Preparacion = "Acompañados con guacamole, crema ácida, frijol refrito y salsa hot. Una bomba divina.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "http://malevamag.com/wp-content/uploads/2017/11/CHIRASHI-CAUSA-Osaka-1200x800.jpg",
                            Ingredientes = "Tartar de pescados, mariscos, masago, palta y salsa acevichada.",
                            Nombre = "La Causa Chirashi",
                            Precio = 300,
                            Preparacion = "Preparada por el chef Eddie Castro, un hit de este restaurante ícono de la cocina Nikkei en la ciudad.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "https://neuquen24horas.com/wp-content/uploads/2019/04/436282-24a00532-effe-43a2-a025-27d206875cfb.jpg",
                            Ingredientes = "Puede ser de carne de vaca o de pollo y va acompañado de papas fritas gruesas y crocantes.",
                            Nombre = "Milanesas con papas fritas",
                            Precio = 250,
                            Preparacion = "Fritas.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "https://imag.bonviveur.es/articulos/lasana-de-verduras.jpg",
                            Ingredientes = "Elaborado una bechamel de champiñones que aporta un toque especial al plato.",
                            Nombre = "Lasaña de verduras",
                            Precio = 200,
                            Preparacion = "Una receta italiana en la que se intercalan láminas de pasta con relleno al gusto, se napa con bechamel, terminando su preparación en el horno.",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "https://imag.bonviveur.es/articulos/macarrones-al-horno-con-carne-picada.jpg",
                            Ingredientes = "Una capa de bechamel antes del queso.",
                            Nombre = "Macarrones al horno",
                            Precio = 310,
                            Preparacion = "Llevan como “extra” una buena dosis de queso gratinado.",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "https://dam.cocinafacil.com.mx/wp-content/uploads/2015/05/costillas-de-cerdo-barbecue.jpg",
                            Ingredientes = "Un costillar de costilla corta de cerdo.",
                            Nombre = "Costillas de cerdo",
                            Precio = 350,
                            Preparacion = "Braseadas con salsa BBQ.",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "https://dam.cocinafacil.com.mx/wp-content/uploads/2020/04/pechuga-a-la-parilla.jpg",
                            Ingredientes = "2 pechugas partidas a la mitad.",
                            Nombre = "Pechuga a la parrilla",
                            Precio = 250,
                            Preparacion = "En una parrilla o sartén caliente asa las pechugas con mantequilla, salpimienta.",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "https://imag.bonviveur.es/articulos/presentacion-principal-de-la-pizza-pepperoni.jpg",
                            Ingredientes = "Se trata de una pizza con base de salsa de tomate, mozzarella y pepperoni.",
                            Nombre = "Pizza pepperoni",
                            Precio = 550,
                            Preparacion = "alami curado hecho a base de carne de cerdo y de vaca mezclados y sazonados con pimentón.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "https://imag.bonviveur.es/articulos/foto-final-del-coctel-white-lady.jpg",
                            Ingredientes = "Ginebra, TripleSec, Jugo de limon, Azucar, 1 Clara de huevo.",
                            Nombre = "White Lady",
                            Precio = 150,
                            Preparacion = "El cóctel original llevaba crema de menta.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "https://imag.bonviveur.es/articulos/foto-principal-sangria.jpg",
                            Ingredientes = "Vino, azúcar, trozos de fruta y alguna bebida carbonatada.",
                            Nombre = "Sangría",
                            Precio = 120,
                            Preparacion = "Hay diferentes tipos de sangrías, con vino blanco o con champagne, pero la clásica española es la que se hace con vino tinto.",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "https://imag.bonviveur.es/articulos/helado-de-oreo.jpg",
                            Ingredientes = "Galletas Oreo.",
                            Nombre = "Helado de Oreo",
                            Precio = 100,
                            Preparacion = "La receta del helado de Oreo que hoy te proponemos tiene pocos ingredientes pues queremos que no le roben el protagonismo a la galleta.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "https://imag.bonviveur.es/articulos/presentacion-de-la-tarta-de-platano.jpg",
                            Ingredientes = "Platanos.",
                            Nombre = "Tarta de plátano",
                            Precio = 180,
                            Preparacion = "Una tarta al más puro estilo estadounidense, con una base de masa de pie y un relleno que alterna una crema pastelera enriquecida con plátano fresco en rodajas.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "https://imag.bonviveur.es/articulos/ensalada-de-judias-verdes-con-tomate-y-huevo-cocido.jpg",
                            Ingredientes = "La temporada de judías verdes ya llega a su fin y es momento de aprovecharlas.",
                            Nombre = "Ensalada de judías verdes con tomate y huevo cocido",
                            Precio = 100,
                            Preparacion = "En esta ensalada, de preparación muy sencilla, las comemos frías y las combinamos con huevo cocido y tomate.",
                            TipoMercaderiaId = 7
                        });
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia");

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Entrada"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minutas"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensaladas"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cervezas Artesanales"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Api_Restful.Domain.Entities.FormaEntrega", "FormaEntrega")
                        .WithMany("Comandas")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.ComandaMercaderia", b =>
                {
                    b.HasOne("Api_Restful.Domain.Entities.Comanda", "Comanda")
                        .WithMany("ComandasMercaderias")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_Restful.Domain.Entities.Mercaderia", "Mercaderia")
                        .WithMany("ComandaMercaderia")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.Mercaderia", b =>
                {
                    b.HasOne("Api_Restful.Domain.Entities.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderias")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ComandasMercaderias");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.FormaEntrega", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.Mercaderia", b =>
                {
                    b.Navigation("ComandaMercaderia");
                });

            modelBuilder.Entity("Api_Restful.Domain.Entities.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderias");
                });
#pragma warning restore 612, 618
        }
    }
}
